[project]
name = "optima-vis"
version = "0.1.0"
description = "A visualization tool for neural network optimizers"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "pytest>=8.4.2",
    "torch>=2.8.0",
]
